import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QPushButton, QLabel, QFileDialog
from PyQt6.QtCore import QSize, Qt, QTimer
import cv2
from PyQt6.QtGui import QImage, QPixmap, QIcon, QFont
import Classifier

current_gesture = 'info' 
modeGestures = False
line = ''

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        
        self.setWindowTitle("ЖЕСТ")
        self.setFixedSize(QSize(820, 612))
        self.setStyleSheet("background-color: #F1F1F1;")

        self.buttonInfo = QPushButton(self)
        self.buttonInfo.setGeometry(10, 10, 100, 100)
        self.buttonInfo.setIcon(QIcon('source/info.png'))
        self.buttonInfo.setIconSize(QSize(100,100))
        self.buttonInfo.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonInfo.setCheckable(True)
        self.buttonInfo.clicked.connect(self.open_info_window)

        self.buttonSettings = QPushButton(self)
        self.buttonSettings.setGeometry(710, 10, 100, 100)
        self.buttonSettings.setIcon(QIcon('source/settings.png'))
        self.buttonSettings.setIconSize(QSize(100,100))
        self.buttonSettings.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonSettings.setCheckable(True)
        self.buttonSettings.clicked.connect(self.open_settings_window)

        self.labelGHEST = QLabel(self)
        pixmap = QPixmap('source/logo.png')
        scaled_pixmap = pixmap.scaled(100, 37)
        self.labelGHEST.setPixmap(scaled_pixmap)
        self.labelGHEST.move(360,20)

        self.buttonFirst = QPushButton(self)
        self.buttonFirst.setGeometry(370, 552, 10, 10)
        self.buttonFirst.setStyleSheet("background-color: black; border-radius: 5px;")

        self.buttonSecond = QPushButton(self)
        self.buttonSecond.setGeometry(390, 552, 10, 10)
        self.buttonSecond.setStyleSheet("background-color: #8C8C8C; border-radius: 5px;")
        self.buttonSecond.setCheckable(True)
        self.buttonSecond.clicked.connect(self.open_dir_window)

        self.buttonThird = QPushButton(self)
        self.buttonThird.setGeometry(410, 552, 10, 10)
        self.buttonThird.setStyleSheet("background-color: #8C8C8C; border-radius: 5px;")
        self.buttonThird.setCheckable(True)
        self.buttonThird.clicked.connect(self.open_start_window)
                
        self.buttonGestures = QPushButton(self)
        self.draw_current_gesture()
        self.buttonGestures.clicked.connect(self.draw_gesture)

        self.camera_label = QLabel(self)
        self.camera_label.setGeometry(212, 166, 395, 293)
        self.cap = cv2.VideoCapture(0)
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.display_webcam_feed)
        self.timer.start(200)
        
        self.label = QLabel(self)
        self.label.setText("покажите в веб-камеру руку и сделайте какой-либо жест")
        self.label.setGeometry(170,60,500,100)
        font = QFont("Montserrat", 12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #8C8C8C;")

        self.show()
    
    def display_webcam_feed(self):
        self.success, self.image = self.cap.read()
        if self.success:
            self.image = cv2.flip(self.image, 1)
            self.imageRGB = cv2.cvtColor(self.image, cv2.COLOR_BGR2RGB)
            cv2.rectangle(self.imageRGB, (0, 0), (638, 478), (140, 140, 140), 4)
            h, w, ch = self.imageRGB.shape
            bytes_per_line = ch * w
            convert_to_Qt_format = QImage(self.imageRGB.data, w, h, bytes_per_line, QImage.Format.Format_RGB888)
            p = convert_to_Qt_format.scaled(395, 293, Qt.AspectRatioMode.KeepAspectRatio)
            self.camera_label.setPixmap(QPixmap.fromImage(p))
        
    def draw_current_gesture(self):
        global current_gesture
        path = 'source/' + current_gesture + '.png'
        if current_gesture == 'three2':
            path = 'source/Three-2.png'
        self.buttonGestures.setGeometry(360, 475, 70, 70)
        self.buttonGestures.setIcon(QIcon(path))
        self.buttonGestures.setIconSize(QSize(50,50))
        self.buttonGestures.setStyleSheet("border: none; margin: 0px; padding: 0px;")

    def draw_gesture(self):
        global current_gesture
        current_gesture = Classifier.get_class_number(self.imageRGB, True)
        self.draw_current_gesture()

    def open_dir_window(self):
        self.cap.release()
        self.DirWindow = DirWindow()
        self.close()
        self.DirWindow.show()

    def open_start_window(self):
        self.cap.release()
        self.StartWindow = StartWindow()
        self.close()
        self.StartWindow.show()

    def open_info_window(self):
        self.cap.release()
        self.InfoWindow = InfoWindow()
        self.close()
        self.InfoWindow.show()

    def open_settings_window(self):
        self.cap.release()
        self.SettingsWindow = SettingsWindow()
        self.close()
        self.SettingsWindow.show()

class DirWindow(QMainWindow):
    def __init__(self):
        super().__init__()
    
        self.setWindowTitle("ЖЕСТ")
        self.setFixedSize(QSize(820, 612))
        self.setStyleSheet("background-color: #F1F1F1;")

        self.buttonInfo = QPushButton(self)
        self.buttonInfo.setGeometry(10, 10, 100, 100)
        self.buttonInfo.setIcon(QIcon('source/info.png'))
        self.buttonInfo.setIconSize(QSize(100,100))
        self.buttonInfo.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonInfo.setCheckable(True)
        self.buttonInfo.clicked.connect(self.open_info_window)

        self.buttonSettings = QPushButton(self)
        self.buttonSettings.setGeometry(710, 10, 100, 100)
        self.buttonSettings.setIcon(QIcon('source/settings.png'))
        self.buttonSettings.setIconSize(QSize(100,100))
        self.buttonSettings.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonSettings.setCheckable(True)
        self.buttonSettings.clicked.connect(self.open_settings_window)

        self.labelGHEST = QLabel(self)
        pixmap = QPixmap('source/logo.png')
        scaled_pixmap = pixmap.scaled(100, 37)
        self.labelGHEST.setPixmap(scaled_pixmap)
        self.labelGHEST.move(360,20)

        self.buttonFirst = QPushButton(self)
        self.buttonFirst.setGeometry(370, 552, 10, 10)
        self.buttonFirst.setStyleSheet("background-color: #8C8C8C; border-radius: 5px;")
        self.buttonFirst.setCheckable(True)
        self.buttonFirst.clicked.connect(self.open_main_window)

        self.buttonSecond = QPushButton(self)
        self.buttonSecond.setGeometry(390, 552, 10, 10)
        self.buttonSecond.setStyleSheet("background-color: black; border-radius: 5px;")

        self.buttonThird = QPushButton(self)
        self.buttonThird.setGeometry(410, 552, 10, 10)
        self.buttonThird.setStyleSheet("background-color: #8C8C8C; border-radius: 5px;")
        self.buttonThird.setCheckable(True)
        self.buttonThird.clicked.connect(self.open_start_window)   
        
        self.label = QLabel(self)
        self.label.setText("рассортируйте изображения в один клик")
        self.label.setGeometry(240,60,350,100)
        font = QFont("Montserrat", 12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #8C8C8C;")   

        self.buttonDir = QPushButton(self)
        self.buttonDir.setGeometry(300, 200, 200, 200)
        self.buttonDir.setIcon(QIcon('source/dir.png'))
        self.buttonDir.setIconSize(QSize(200,200))
        self.buttonDir.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonDir.setCheckable(True)
        self.buttonDir.clicked.connect(self.sort_images)  

        self.buttonChooseDir = QPushButton(self)
        self.buttonChooseDir.setGeometry(300, 450, 200, 80)
        self.buttonChooseDir.setStyleSheet("background-color: #8C8C8C; border: none; margin: 0px; padding: 0px; border-radius: 40px; color: white; font-family: Montserrat; font-size: 16px")
        self.buttonChooseDir.setText("Выбрать папку")
        self.buttonChooseDir.setCheckable(True)
        self.buttonChooseDir.clicked.connect(self.sort_images)  

    def sort_images(self):
        line = QFileDialog.getExistingDirectory(self, "Выберете папку с изображениями", ".")
        Classifier.run_sorted(line)

    def open_main_window(self):
        self.MainWindow = MainWindow()
        self.close()
        self.MainWindow.show()

    def open_start_window(self):
        self.StartWindow = StartWindow()
        self.close()
        self.StartWindow.show()

    def open_info_window(self):
        self.InfoWindow = InfoWindow()
        self.close()
        self.InfoWindow.show()

    def open_settings_window(self):
        self.SettingsWindow = SettingsWindow()
        self.close()
        self.SettingsWindow.show()  

class StartWindow(QMainWindow):
    def __init__(self):
        super().__init__()
            
        self.setWindowTitle("ЖЕСТ")
        self.setFixedSize(QSize(820, 612))
        self.setStyleSheet("background-color: #F1F1F1;")

        self.buttonInfo = QPushButton(self)
        self.buttonInfo.setGeometry(10, 10, 100, 100)
        self.buttonInfo.setIcon(QIcon('source/info.png'))
        self.buttonInfo.setIconSize(QSize(100,100))
        self.buttonInfo.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonInfo.setCheckable(True)
        self.buttonInfo.clicked.connect(self.open_info_window)

        self.buttonSettings = QPushButton(self)
        self.buttonSettings.setGeometry(710, 10, 100, 100)
        self.buttonSettings.setIcon(QIcon('source/settings.png'))
        self.buttonSettings.setIconSize(QSize(100,100))
        self.buttonSettings.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonSettings.setCheckable(True)
        self.buttonSettings.clicked.connect(self.open_settings_window)

        self.labelGHEST = QLabel(self)
        pixmap = QPixmap('source/logo.png')
        scaled_pixmap = pixmap.scaled(100, 37)
        self.labelGHEST.setPixmap(scaled_pixmap)
        self.labelGHEST.move(360,20)
        
        self.buttonEnable = QPushButton(self)
        self.buttonEnable.setGeometry(680, 530, 116, 50)
        self.buttonEnable.setStyleSheet("background-color: #8C8C8C; border: none; margin: 0px; padding: 0px; border-radius: 25px;")
        
        self.buttonMode = QPushButton(self)
        if (modeGestures == False):
            self.buttonMode.setGeometry(685, 535, 40, 40)
            self.buttonMode.setStyleSheet("background-color: black; border: none; margin: 0px; padding: 0px; border-radius: 20px;")
        else:
            self.buttonMode.setGeometry(751, 535, 40, 40)
            self.buttonMode.setStyleSheet("background-color: white; border: none; margin: 0px; padding: 0px; border-radius: 20px;")
        self.buttonMode.setCheckable(True)
        self.buttonMode.clicked.connect(self.enabled_mode)

        self.buttonFirst = QPushButton(self)
        self.buttonFirst.setGeometry(370, 552, 10, 10)
        self.buttonFirst.setStyleSheet("background-color: #8C8C8C; border-radius: 5px;")
        self.buttonFirst.setCheckable(True)
        self.buttonFirst.clicked.connect(self.open_main_window)

        self.buttonSecond = QPushButton(self)
        self.buttonSecond.setGeometry(390, 552, 10, 10)
        self.buttonSecond.setStyleSheet("background-color: #8C8C8C; border-radius: 5px;")
        self.buttonSecond.setCheckable(True)
        self.buttonSecond.clicked.connect(self.open_dir_window)

        self.buttonThird = QPushButton(self)
        self.buttonThird.setGeometry(410, 552, 10, 10)
        self.buttonThird.setStyleSheet("background-color: black; border-radius: 5px;")
        
        self.label1 = QLabel(self)
        self.label1.setText("Управляйте вашим\nкомпьютером\nс помощью жестов")
        self.label1.setGeometry(230,100,350,110)
        font = QFont("Montserrat", 24)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color: black; text-align: center")   
        self.label1.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.label2 = QLabel(self)
        self.label2.setText("Попробуйте прямо сейчас")
        self.label2.setGeometry(180,300,500,50)
        font = QFont("Montserrat", 24)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: #8C8C8C; text-align: center")   
        self.label2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.labelGHEST1 = QLabel(self)
        self.labelGHEST1.setPixmap(scaled_pixmap)
        self.labelGHEST1.move(360,350)

        self.Arrow = QPushButton(self)
        self.Arrow.setGeometry(500, 300, 200, 200)
        self.Arrow.setIcon(QIcon('source/arrow.png'))
        self.Arrow.setIconSize(QSize(200,200))
        self.Arrow.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.Arrow.lower()

    def enabled_mode(self):
        global modeGestures
        modeGestures = not modeGestures
        if (modeGestures == False):
            self.buttonMode.setGeometry(685, 535, 40, 40)
            self.buttonMode.setStyleSheet("background-color: black; border: none; margin: 0px; padding: 0px; border-radius: 20px;")
            Classifier.stop_classifier()
        else:
            self.buttonMode.setGeometry(751, 535, 40, 40)
            self.buttonMode.setStyleSheet("background-color: white; border: none; margin: 0px; padding: 0px; border-radius: 20px;")
            Classifier.run_classifier()

    def open_main_window(self):
        self.MainWindow = MainWindow()
        self.close()
        self.MainWindow.show()

    def open_dir_window(self):
        self.DirWindow = DirWindow()
        self.close()
        self.DirWindow.show()

    def open_info_window(self):
        self.InfoWindow = InfoWindow()
        self.close()
        self.InfoWindow.show()

    def open_settings_window(self):
        self.SettingsWindow = SettingsWindow()
        self.close()
        self.SettingsWindow.show()
        
class InfoWindow(QMainWindow):
    def __init__(self):
        super().__init__()
            
        self.setWindowTitle("ЖЕСТ")
        self.setFixedSize(QSize(820, 612))
        self.setStyleSheet("background-color: #F1F1F1;")

        self.buttonInfo = QPushButton(self)
        self.buttonInfo.setGeometry(10, 10, 100, 100)
        self.buttonInfo.setIcon(QIcon('source/info.png'))
        self.buttonInfo.setIconSize(QSize(100,100))
        self.buttonInfo.setStyleSheet("border: none; margin: 0px; padding: 0px;")

        self.buttonSettings = QPushButton(self)
        self.buttonSettings.setGeometry(710, 10, 100, 100)
        self.buttonSettings.setIcon(QIcon('source/settings.png'))
        self.buttonSettings.setIconSize(QSize(100,100))
        self.buttonSettings.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonSettings.setCheckable(True)
        self.buttonSettings.clicked.connect(self.open_settings_window)

        self.labelGHEST = QLabel(self)
        pixmap = QPixmap('source/logo.png')
        scaled_pixmap = pixmap.scaled(100, 37)
        self.labelGHEST.setPixmap(scaled_pixmap)
        self.labelGHEST.move(360,20)

        self.Call = QPushButton(self)
        self.Call.setGeometry(10, 120, 85, 85)
        self.Call.setIcon(QIcon('source/Call.png'))
        self.Call.setIconSize(QSize(60,60))
        self.Call.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelCall = QLabel(self)
        self.labelCall.setGeometry(30, 210, 85, 20)
        self.labelCall.setText('Call')
        font = QFont("Montserrat", 12)
        self.labelCall.setFont(font)
        self.labelCall.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Like = QPushButton(self)
        self.Like.setGeometry(100, 120, 85, 85)
        self.Like.setIcon(QIcon('source/Like.png'))
        self.Like.setIconSize(QSize(60,60))
        self.Like.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelLike = QLabel(self)
        self.labelLike.setGeometry(130, 210, 85, 20)
        self.labelLike.setText('Like')
        self.labelLike.setFont(font)
        self.labelLike.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Dislike = QPushButton(self)
        self.Dislike.setGeometry(190, 120, 85, 85)
        self.Dislike.setIcon(QIcon('source/Dislike.png'))
        self.Dislike.setIconSize(QSize(60,60))
        self.Dislike.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelDislike = QLabel(self)
        self.labelDislike.setGeometry(210, 210, 85, 20)
        self.labelDislike.setText('Dislike')
        self.labelDislike.setFont(font)
        self.labelDislike.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Mute = QPushButton(self)
        self.Mute.setGeometry(280, 120, 85, 85)
        self.Mute.setIcon(QIcon('source/Mute.png'))
        self.Mute.setIconSize(QSize(60,60))
        self.Mute.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelMute = QLabel(self)
        self.labelMute.setGeometry(310, 210, 85, 20)
        self.labelMute.setText('Mute')
        self.labelMute.setFont(font)
        self.labelMute.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Fist = QPushButton(self)
        self.Fist.setGeometry(370, 120, 85, 85)
        self.Fist.setIcon(QIcon('source/Fist.png'))
        self.Fist.setIconSize(QSize(60,60))
        self.Fist.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelFist = QLabel(self)
        self.labelFist.setGeometry(408, 210, 85, 20)
        self.labelFist.setText('Fist')
        self.labelFist.setFont(font)
        self.labelFist.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Palm = QPushButton(self)
        self.Palm.setGeometry(460, 120, 85, 85)
        self.Palm.setIcon(QIcon('source/Palm.png'))
        self.Palm.setIconSize(QSize(60,60))
        self.Palm.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelPalm = QLabel(self)
        self.labelPalm.setGeometry(480, 210, 85, 20)
        self.labelPalm.setText('Palm')
        self.labelPalm.setFont(font)
        self.labelPalm.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Ok = QPushButton(self)
        self.Ok.setGeometry(550, 120, 85, 85)
        self.Ok.setIcon(QIcon('source/Ok.png'))
        self.Ok.setIconSize(QSize(60,60))
        self.Ok.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelOk = QLabel(self)
        self.labelOk.setGeometry(583, 210, 85, 20)
        self.labelOk.setText('Ok')
        self.labelOk.setFont(font)
        self.labelOk.setStyleSheet("color: #8C8C8C; text-align: center")

        self.One = QPushButton(self)
        self.One.setGeometry(640, 120, 85, 85)
        self.One.setIcon(QIcon('source/One.png'))
        self.One.setIconSize(QSize(60,60))
        self.One.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelOne = QLabel(self)
        self.labelOne.setGeometry(668, 210, 85, 20)
        self.labelOne.setText('One')
        self.labelOne.setFont(font)
        self.labelOne.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Four = QPushButton(self)
        self.Four.setGeometry(730, 120, 85, 85)
        self.Four.setIcon(QIcon('source/Four.png'))
        self.Four.setIconSize(QSize(60,60))
        self.Four.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelFour = QLabel(self)
        self.labelFour.setGeometry(750, 210, 85, 20)
        self.labelFour.setText('Four')
        self.labelFour.setFont(font)
        self.labelFour.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Peace = QPushButton(self)
        self.Peace.setGeometry(10, 350, 85, 85)
        self.Peace.setIcon(QIcon('source/Peace.png'))
        self.Peace.setIconSize(QSize(60,60))
        self.Peace.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelPeace = QLabel(self)
        self.labelPeace.setGeometry(30, 435, 85, 20)
        self.labelPeace.setText('Peace')
        self.labelPeace.setFont(font)
        self.labelPeace.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Peace_inverted = QPushButton(self)
        self.Peace_inverted.setGeometry(100, 350, 85, 85)
        self.Peace_inverted.setIcon(QIcon('source/Peace_inverted.png'))
        self.Peace_inverted.setIconSize(QSize(60,60))
        self.Peace_inverted.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelPeace_inverted = QLabel(self)
        self.labelPeace_inverted.setGeometry(110, 435, 85, 40)
        self.labelPeace_inverted.setText('  Peace  \ninverted')
        self.labelPeace_inverted.setFont(font)
        self.labelPeace_inverted.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Rock = QPushButton(self)
        self.Rock.setGeometry(190, 350, 85, 85)
        self.Rock.setIcon(QIcon('source/Rock.png'))
        self.Rock.setIconSize(QSize(60,60))
        self.Rock.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelRock = QLabel(self)
        self.labelRock.setGeometry(210, 435, 85, 20)
        self.labelRock.setText('Rock')
        self.labelRock.setFont(font)
        self.labelRock.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Three = QPushButton(self)
        self.Three.setGeometry(280, 350, 85, 85)
        self.Three.setIcon(QIcon('source/Three.png'))
        self.Three.setIconSize(QSize(60,60))
        self.Three.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelThree = QLabel(self)
        self.labelThree.setGeometry(300, 435, 85, 20)
        self.labelThree.setText('Three')
        self.labelThree.setFont(font)
        self.labelThree.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Stop = QPushButton(self)
        self.Stop.setGeometry(370, 350, 85, 85)
        self.Stop.setIcon(QIcon('source/Stop.png'))
        self.Stop.setIconSize(QSize(60,60))
        self.Stop.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelStop = QLabel(self)
        self.labelStop.setGeometry(400, 435, 85, 20)
        self.labelStop.setText('Stop')
        self.labelStop.setFont(font)
        self.labelStop.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Stop_inverted = QPushButton(self)
        self.Stop_inverted.setGeometry(460, 350, 85, 85)
        self.Stop_inverted.setIcon(QIcon('source/Stop_inverted.png'))
        self.Stop_inverted.setIconSize(QSize(60,60))
        self.Stop_inverted.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelStop_inverted = QLabel(self)
        self.labelStop_inverted.setGeometry(470, 435, 85, 40)
        self.labelStop_inverted.setText('   Stop   \ninverted')
        self.labelStop_inverted.setFont(font)
        self.labelStop_inverted.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Three_2 = QPushButton(self)
        self.Three_2.setGeometry(550, 350, 85, 85)
        self.Three_2.setIcon(QIcon('source/Three-2.png'))
        self.Three_2.setIconSize(QSize(60,60))
        self.Three_2.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelThree_2 = QLabel(self)
        self.labelThree_2.setGeometry(560, 435, 85, 20)
        self.labelThree_2.setText('Three-2')
        self.labelThree_2.setFont(font)
        self.labelThree_2.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Two_up = QPushButton(self)
        self.Two_up.setGeometry(640, 350, 85, 85)
        self.Two_up.setIcon(QIcon('source/Two_up.png'))
        self.Two_up.setIconSize(QSize(60,60))
        self.Two_up.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelTwo_up = QLabel(self)
        self.labelTwo_up.setGeometry(650, 435, 85, 20)
        self.labelTwo_up.setText('Two up')
        self.labelTwo_up.setFont(font)
        self.labelTwo_up.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Two_up_inverted = QPushButton(self)
        self.Two_up_inverted.setGeometry(730, 350, 85, 85)
        self.Two_up_inverted.setIcon(QIcon('source/Two_up_inverted.png'))
        self.Two_up_inverted.setIconSize(QSize(60,60))
        self.Two_up_inverted.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelTwo_up_inverted = QLabel(self)
        self.labelTwo_up_inverted.setGeometry(740, 435, 85, 40)
        self.labelTwo_up_inverted.setText(' Two up \ninverted')
        self.labelTwo_up_inverted.setFont(font)
        self.labelTwo_up_inverted.setStyleSheet("color: #8C8C8C; text-align: center")

        self.buttonBack = QPushButton(self)
        self.buttonBack.setGeometry(10, 500, 100, 100)
        self.buttonBack.setIcon(QIcon('source/Back.png'))
        self.buttonBack.setIconSize(QSize(60,60))
        self.buttonBack.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonBack.setCheckable(True)
        self.buttonBack.clicked.connect(self.go_back)

    def go_back(self):
        self.Window = MainWindow()
        self.close()
        self.Window.show()  

    def open_settings_window(self):
        self.SettingsWindow = SettingsWindow()
        self.close()
        self.SettingsWindow.show()    

class SettingsWindow(QMainWindow):
    def __init__(self):
        super().__init__()
            
        self.setWindowTitle("ЖЕСТ")
        self.setFixedSize(QSize(820, 612))
        self.setStyleSheet("background-color: #F1F1F1;")

        self.buttonInfo = QPushButton(self)
        self.buttonInfo.setGeometry(10, 10, 100, 100)
        self.buttonInfo.setIcon(QIcon('source/info.png'))
        self.buttonInfo.setIconSize(QSize(100,100))
        self.buttonInfo.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonInfo.setCheckable(True)
        self.buttonInfo.clicked.connect(self.open_info_window)

        self.buttonSettings = QPushButton(self)
        self.buttonSettings.setGeometry(710, 10, 100, 100)
        self.buttonSettings.setIcon(QIcon('source/settings.png'))
        self.buttonSettings.setIconSize(QSize(100,100))
        self.buttonSettings.setStyleSheet("border: none; margin: 0px; padding: 0px;")

        self.labelGHEST = QLabel(self)
        pixmap = QPixmap('source/logo.png')
        scaled_pixmap = pixmap.scaled(100, 37)
        self.labelGHEST.setPixmap(scaled_pixmap)
        self.labelGHEST.move(360,20)

        file = open('information.txt','r')
        
        self.Call = QPushButton(self)
        self.Call.setGeometry(10, 120, 85, 85)
        self.Call.setIcon(QIcon('source/Call.png'))
        self.Call.setIconSize(QSize(60,60))
        self.Call.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelCall = QLabel(self)
        self.labelCall.setGeometry(30, 210, 85, 40)
        self.lineCall = file.readline()
        self.labelCall.setText(self.lineCall)
        font = QFont("Montserrat", 12)
        self.labelCall.setFont(font)
        self.labelCall.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Like = QPushButton(self)
        self.Like.setGeometry(100, 120, 85, 85)
        self.Like.setIcon(QIcon('source/Like.png'))
        self.Like.setIconSize(QSize(60,60))
        self.Like.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelLike = QLabel(self)
        self.labelLike.setGeometry(130, 210, 85, 40)
        self.lineLike = file.readline()
        self.labelLike.setText(self.lineLike)
        self.labelLike.setFont(font)
        self.labelLike.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Dislike = QPushButton(self)
        self.Dislike.setGeometry(190, 120, 85, 85)
        self.Dislike.setIcon(QIcon('source/Dislike.png'))
        self.Dislike.setIconSize(QSize(60,60))
        self.Dislike.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelDislike = QLabel(self)
        self.labelDislike.setGeometry(210, 210, 85, 40)
        self.lineDislike = file.readline()
        self.labelDislike.setText(self.lineDislike)
        self.labelDislike.setFont(font)
        self.labelDislike.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Mute = QPushButton(self)
        self.Mute.setGeometry(280, 120, 85, 85)
        self.Mute.setIcon(QIcon('source/Mute.png'))
        self.Mute.setIconSize(QSize(60,60))
        self.Mute.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelMute = QLabel(self)
        self.labelMute.setGeometry(290, 210, 90, 40)
        self.lineMute = file.readline()
        self.labelMute.setText(self.lineMute)
        self.labelMute.setFont(font)
        self.labelMute.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Fist = QPushButton(self)
        self.Fist.setGeometry(370, 120, 85, 85)
        self.Fist.setIcon(QIcon('source/Fist.png'))
        self.Fist.setIconSize(QSize(60,60))
        self.Fist.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelFist = QLabel(self)
        self.labelFist.setGeometry(408, 210, 85, 40)
        self.lineFist = file.readline()
        self.labelFist.setText(self.lineFist)
        self.labelFist.setFont(font)
        self.labelFist.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Palm = QPushButton(self)
        self.Palm.setGeometry(460, 120, 85, 85)
        self.Palm.setIcon(QIcon('source/Palm.png'))
        self.Palm.setIconSize(QSize(60,60))
        self.Palm.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelPalm = QLabel(self)
        self.labelPalm.setGeometry(480, 210, 85, 40)
        self.linePalm = file.readline()
        self.labelPalm.setText(self.linePalm)
        self.labelPalm.setFont(font)
        self.labelPalm.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Ok = QPushButton(self)
        self.Ok.setGeometry(550, 120, 85, 85)
        self.Ok.setIcon(QIcon('source/Ok.png'))
        self.Ok.setIconSize(QSize(60,60))
        self.Ok.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelOk = QLabel(self)
        self.labelOk.setGeometry(583, 210, 85, 40)
        self.lineOk = file.readline()
        self.labelOk.setText(self.lineOk)
        self.labelOk.setFont(font)
        self.labelOk.setStyleSheet("color: #8C8C8C; text-align: center")

        self.One = QPushButton(self)
        self.One.setGeometry(640, 120, 85, 85)
        self.One.setIcon(QIcon('source/One.png'))
        self.One.setIconSize(QSize(60,60))
        self.One.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelOne = QLabel(self)
        self.labelOne.setGeometry(668, 210, 85, 40)
        self.lineOne = file.readline()
        self.labelOne.setText(self.lineOne)
        self.labelOne.setFont(font)
        self.labelOne.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Four = QPushButton(self)
        self.Four.setGeometry(730, 120, 85, 85)
        self.Four.setIcon(QIcon('source/Four.png'))
        self.Four.setIconSize(QSize(60,60))
        self.Four.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelFour = QLabel(self)
        self.labelFour.setGeometry(750, 210, 85, 40)
        self.lineFour = file.readline()
        self.labelFour.setText(self.lineFour)
        self.labelFour.setFont(font)
        self.labelFour.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Peace = QPushButton(self)
        self.Peace.setGeometry(10, 350, 85, 85)
        self.Peace.setIcon(QIcon('source/Peace.png'))
        self.Peace.setIconSize(QSize(60,60))
        self.Peace.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelPeace = QLabel(self)
        self.labelPeace.setGeometry(30, 435, 85, 40)
        self.linePeace = file.readline()
        self.labelPeace.setText(self.linePeace)
        self.labelPeace.setFont(font)
        self.labelPeace.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Peace_inverted = QPushButton(self)
        self.Peace_inverted.setGeometry(100, 350, 85, 85)
        self.Peace_inverted.setIcon(QIcon('source/Peace_inverted.png'))
        self.Peace_inverted.setIconSize(QSize(60,60))
        self.Peace_inverted.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelPeace_inverted = QLabel(self)
        self.labelPeace_inverted.setGeometry(110, 435, 85, 40)
        self.linePeace_inverted = file.readline()
        self.labelPeace_inverted.setText(self.linePeace_inverted)
        self.labelPeace_inverted.setFont(font)
        self.labelPeace_inverted.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Rock = QPushButton(self)
        self.Rock.setGeometry(190, 350, 85, 85)
        self.Rock.setIcon(QIcon('source/Rock.png'))
        self.Rock.setIconSize(QSize(60,60))
        self.Rock.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelRock = QLabel(self)
        self.labelRock.setGeometry(210, 435, 85, 40)
        self.lineRock = file.readline()
        self.labelRock.setText(self.lineRock)
        self.labelRock.setFont(font)
        self.labelRock.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Three = QPushButton(self)
        self.Three.setGeometry(280, 350, 85, 85)
        self.Three.setIcon(QIcon('source/Three.png'))
        self.Three.setIconSize(QSize(60,60))
        self.Three.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelThree = QLabel(self)
        self.labelThree.setGeometry(280, 435, 85, 40)
        self.lineThree = file.readline()
        self.labelThree.setText(self.lineThree)
        self.labelThree.setFont(font)
        self.labelThree.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Stop = QPushButton(self)
        self.Stop.setGeometry(370, 350, 85, 85)
        self.Stop.setIcon(QIcon('source/Stop.png'))
        self.Stop.setIconSize(QSize(60,60))
        self.Stop.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelStop = QLabel(self)
        self.labelStop.setGeometry(370, 435, 85, 40)
        self.lineStop = file.readline()
        self.labelStop.setText(self.lineStop)
        self.labelStop.setFont(font)
        self.labelStop.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Stop_inverted = QPushButton(self)
        self.Stop_inverted.setGeometry(440, 350, 85, 85)
        self.Stop_inverted.setIcon(QIcon('source/Stop_inverted.png'))
        self.Stop_inverted.setIconSize(QSize(60,60))
        self.Stop_inverted.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelStop_inverted = QLabel(self)
        self.labelStop_inverted.setGeometry(470, 435, 85, 40)
        self.lineStop_inverted = file.readline()
        self.labelStop_inverted.setText(self.lineStop_inverted)
        self.labelStop_inverted.setFont(font)
        self.labelStop_inverted.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Three_2 = QPushButton(self)
        self.Three_2.setGeometry(550, 350, 85, 85)
        self.Three_2.setIcon(QIcon('source/Three-2.png'))
        self.Three_2.setIconSize(QSize(60,60))
        self.Three_2.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelThree_2 = QLabel(self)
        self.labelThree_2.setGeometry(560, 435, 85, 40)
        self.lineThree_2 = file.readline()
        self.labelThree_2.setText(self.lineThree_2)
        self.labelThree_2.setFont(font)
        self.labelThree_2.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Two_up = QPushButton(self)
        self.Two_up.setGeometry(640, 350, 85, 85)
        self.Two_up.setIcon(QIcon('source/Two_up.png'))
        self.Two_up.setIconSize(QSize(60,60))
        self.Two_up.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelTwo_up = QLabel(self)
        self.labelTwo_up.setGeometry(650, 435, 85, 40)
        self.lineTwo_up = file.readline()
        self.labelTwo_up.setText(self.lineTwo_up)
        self.labelTwo_up.setFont(font)
        self.labelTwo_up.setStyleSheet("color: #8C8C8C; text-align: center")

        self.Two_up_inverted = QPushButton(self)
        self.Two_up_inverted.setGeometry(730, 350, 85, 85)
        self.Two_up_inverted.setIcon(QIcon('source/Two_up_inverted.png'))
        self.Two_up_inverted.setIconSize(QSize(60,60))
        self.Two_up_inverted.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.labelTwo_up_inverted = QLabel(self)
        self.labelTwo_up_inverted.setGeometry(740, 435, 85, 30)
        self.lineTwo_up_inverted = file.readline()
        self.labelTwo_up_inverted.setText(self.lineTwo_up_inverted)
        self.labelTwo_up_inverted.setFont(font)
        self.labelTwo_up_inverted.setStyleSheet("color: #8C8C8C; text-align: center")

        self.buttonBack = QPushButton(self)
        self.buttonBack.setGeometry(10, 500, 100, 100)
        self.buttonBack.setIcon(QIcon('source/Back.png'))
        self.buttonBack.setIconSize(QSize(60,60))
        self.buttonBack.setStyleSheet("border: none; margin: 0px; padding: 0px;")
        self.buttonBack.setCheckable(True)
        self.buttonBack.clicked.connect(self.go_back)

        file.close()

    def go_back(self):
        self.Window = MainWindow()
        self.close()
        self.Window.show()  

    def open_info_window(self):
        self.InfoWindow = InfoWindow()
        self.close()
        self.InfoWindow.show()     
        
app = QApplication(sys.argv)

window = MainWindow()

app.exec()